/*
 * usart.c
 *
 *  Created on: 18 Aug 2019
 *      Author: me
 */
#include "usart.h"

void InitUSART(){

	//HAL USART IMPLEMENTATION WAS BROKEN WITH NO GPIOS CONFIGURED.
	//HACKED TOGETHER SOMETHING THAT WORKS AND POOLED IT INTO 1 PLACE.
	//WILL DITCH HAL WHEN HAVE TIME TO READ THROUGH THE DOZENS OF REGISTERS. FOR NOW ITS STREAMLINED ONCE INITILIASED.

	GPIO_InitTypeDef GPIO_InitStruct = {0};
	GPIO_InitStruct.Pin = EDGE_DATA_Pin;
	GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
	GPIO_InitStruct.Pull = GPIO_NOPULL;
	GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_MEDIUM;
	GPIO_InitStruct.Alternate = GPIO_AF4_USART3;
	HAL_GPIO_Init(GPIOB, &GPIO_InitStruct);

	__HAL_RCC_USART3_CLK_ENABLE();


	USART3->CR1 &= ~1;
	USART3->CR3 &= ~USART_CR3_DMAT;
	USART3->CR1 |= USART_CR1_TCIE;
	USART3->CR1 |= USART_CR1_FIFOEN;
	USART3->CR3 |= USART_CR3_HDSEL;
	USART3->ISR |= UART_CLEAR_TCF;
	USART3->CR3 |= USART_CR3_DMAT;
	USART3->CR1 |= 1;
}
